vote_post_positive:
  methods: [ POST ]
  path: /post/{postId}/positive
  defaults: { _controller: VoteBundle:PostVote:votePositive }
  requirements:
    postId: \d+

vote_post_negative:
  methods: [ POST ]
  path: /post/{postId}/negative
  defaults: { _controller: VoteBundle:PostVote:voteNegative }
  requirements:
    postId: \d+

vote_post_delete:
  methods: [ DELETE ]
  path: /post/{postId}/delete
  defaults: { _controller: VoteBundle:PostVote:voteRemove }
  requirements:
    postId: \d+



vote_comment_positive:
  methods: [ POST ]
  path: /comment/{commentId}/positive
  defaults: { _controller: VoteBundle:CommentVote:votePositive }
  requirements:
    commentId: \d+

vote_comment_negative:
  methods: [ POST ]
  path: /comment/{commentId}/negative
  defaults: { _controller: VoteBundle:CommentVote:voteNegative }
  requirements:
    commentId: \d+

vote_comment_delete:
  methods: [ DELETE ]
  path: /comment/{commentId}/delete
  defaults: { _controller: VoteBundle:CommentVote:voteRemove }
  requirements:
    commentId: \d+

vote_profile:
  methods: [ GET ]
  path: /profile/vote_type/{vote_type}/content_type/{content_type}/limit/{limit}
  defaults: { _controller: VoteBundle:ProfileVotes:getVotes }
  requirements:
    vote_type: "positive|negative"
    content_type: "post|comment"
    limit: \d+
    cursor: \d+
    profile: \d+