profile_create:
  path: create
  defaults: { _controller: ProfileBundle:Create:create }
  methods: [ PUT ]

profile_update:
  path: '{id}/update'
  defaults: { _controller: ProfileBundle:Update:update }
  methods: [ PUT, PATCH ]
  requirements:
    id: '\d+'
#profile_delete:
#  path: '{id}/delete'
#  defaults: { _controller: ProfileBundle:Delete:delete }
#  methods: [ DELETE ]
#  requirements:
#    id: '\d+'
    
profile_avatar_upload:
  path: '{id}/avatar/upload'
  defaults: { _controller: ProfileBundle:Avatar:upload }
  methods: [ POST ]
  requirements:
    id: '\d+'

profile_avatar_delete:
  path: '{id}/avatar/delete'
  defaults: { _controller: ProfileBundle:AvatarDelete:avatarDelete }
  methods: [ DELETE ]
  requirements:
    id: '\d+'

profile_backdrop_upload:
  path: '{id}/backdrop/upload'
  defaults: { _controller: ProfileBundle:Backdrop:upload }
  methods: [ POST ]
  requirements:
    id: '\d+'

profile_backdrop_delete:
  path: '{id}/backdrop/delete'
  defaults: { _controller: ProfileBundle:Backdrop:delete }
  methods: [ DELETE ]
  requirements:
    id: '\d+'

profile_backdrop_presets:
  path: '/backdrop/presets'
  defaults: { _controller: ProfileBundle:Backdrop:getBackdropPresets }
  methods: [ GET ]

profile_backdrop_set:
  path: '{id}/backdrop/preset/{presetId}/set'
  defaults: { _controller: ProfileBundle:Backdrop:setBackdrop }
  methods: [ POST ]
  requirements:
    id: '\d+'
    presetId: '\d+'
