sign_in:
  path: /sign-in
  defaults:  
    _controller: AuthBundle:SignIn:signIn
  methods: [POST]

sign_up:
  path: /sign-up
  defaults:
    _controller: AuthBundle:SignUp:signUp
  methods: [PUT]

get_token:
  path: /token/get/{token}/{refresh_token}
  defaults:  
    _controller: AuthBundle:RenderToken:render
  methods: [GET]
  
refresh_token:
  path:     /token/refresh
  defaults: 
   _controller: AuthBundle:RefreshToken:refresh 
  methods: [POST]

email_password_recovery:
  path: /password-recovery/email-send
  defaults:
    _controller: AuthBundle:RecoverPasswordByEmail:requestRestorationEmail
  methods: [ PUT ]

email_password_recover_mail:
  path: /password-recovery/email-recover/confirm
  defaults:
    _controller: AuthBundle:RecoverPasswordByEmail:confirmRestorationEmail
  methods: [ POST ]