services:
    auth.service:
      public: true
      class: AuthBundle\Service\AuthService
      arguments: 
        - '@account.repository'
        - '@security.password_encoder'
        - '@security.token_storage'

    auth.event.jwt_created_listener:
        class: AuthBundle\EventListener\JWTCreatedListener
        arguments: ['@profile.service']
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    auth.service.email_confirmation_service:
        class: AuthBundle\Service\EmailConfirmationService
        arguments:
          - '@auth.service'
          - '@mailer'
          - '@auth.repository.confirmation_repository'
          - '%auth.email_code_life_time_min%'
          - '%mailer_email_no_reply%'

    auth.repository.confirmation_repository:
        class: AuthBundle\Repository\ConfirmationRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
          - AuthBundle\Entity\Confirmation

    auth.service.passord_recovery_service:
      class: AuthBundle\Service\PasswordRecoverService
      arguments:
        - '@mailer'
        - '@auth.repository.confirmation_repository'
        - '%auth.email_code_life_time_min%'
        - '%mailer_email_no_reply%'