CommentBundle\Entity\Comment:
  type: entity
  repositoryClass: CommentBundle\Repository\CommentRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false

    votesRating:
      type: integer
      nullable: false
    votesPositive:
      type: integer
      nullable: false
    votesNegative:
      type: integer
      nullable: false
    commentsTotal:
      column: comments_total
      type: integer
      nullable: false
    level:
      type: integer
      nullable: false
    isDeleted:
      column: is_deleted
      type: boolean
      nullable: false

  oneToMany:
    childrenComments:
      targetEntity: CommentBundle\Entity\Comment
      mappedBy: parentComment
  manyToOne:
    post:
      targetEntity: PostBundle\Entity\Post
    parentComment:
      targetEntity: CommentBundle\Entity\Comment
      inversedBy: childrenComments
    profile:
      targetEntity: ProfileBundle\Entity\Profile
  manyToMany:
    attachments:
      targetEntity: AttachmentBundle\Entity\Attachment