search_addition:
  path: '/addition/{query}'
  methods: [ GET ]
  defaults: { _controller: SearchBundle:Search:searchAddition }
search_full:
  path: '/full/{query}'
  methods: [ GET ]
  defaults: { _controller: SearchBundle:Search:searchFull }
  requirements:
    cursor: \d+
