AuthBundle\Entity\Confirmation:
  type: entity
  repositoryClass: AuthBundle\Repository\ConfirmationRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    type:
      type: smallint
      nullable: false
    expires:
      type: datetime
      nullable: false
    updated:
      type: datetime
      nullable: false
    isConfirmed:
      column: is_confirmed
      type: boolean
      nullable: false
    code:
      type: string
      nullable: false
    wasted:
      type: boolean
      nullable: false

  manyToOne:
    account:
      targetEntity: AccountBundle\Entity\Account
