TagBundle\Entity\Tag:
  type: entity
  repositoryClass: TagBundle\Repository\TagRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      unique: true