services:
    app.validate_request:
        public: true
        class: AppBundle\Service\ValidateRequestService
        arguments: ['@form.factory']


    app.swiftmailer.mailer.default.transport:
        class:     Swift_SmtpTransport
        arguments: ['/usr/sbin/sendmail -t']

    app.mailer.default:
        class: Swift_Mailer
        arguments: ['@app.swiftmailer.mailer.default.transport']