services:

  subscribe.repository.subscribe_repository:
    class: SubscribeBundle\Repository\SubscribeRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - SubscribeBundle\Entity\Subscribe

  subscribe.service.subscribe_service:
    public: true
    class: SubscribeBundle\Service\SubscribeService
    arguments:
       - '@profile.service'
       - '@subscribe.repository.subscribe_repository'
       - '@event_dispatcher'

  subscribe.event_listener.update_subscribers_total_listener:
      class: SubscribeBundle\Event\UpdateSubscribersTotalListener
      tags:
        - { name: kernel.event_subscriber }
      arguments:
        - "@subscribe.service.subscribe_service"